In [112]:
z<-matrix(0, 1, 3) #row vector of 0's
z

[,1] [,2] [,3]
[1,] 0    0    0

In [146]:
aa<-matrix(1,3,4)
aa

[,1] [,2] [,3] [,4]
[1,] 1    1    1    1   
[2,] 1    1    1    1   
[3,] 1    1    1    1

In [147]:
det(aa)

ERROR: Error in determinant.matrix(x, logarithm = TRUE, ...): 'x' must be a square matrix


In [113]:
o<-matrix(1, 1, 3) #row vector of 1's
o

[,1] [,2] [,3]
[1,] 1    1    1

In [1]:
x1<-1:10
x2<-1:10

In [2]:
x1==x2

[1] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE

In [59]:
vec<-c(3,2,-5,5,-3,-6,2,1,-3) #llenar por columnas
A<-matrix(vec,3,3) #matrix
vec2<-c(3,4,5)
B<-matrix(vec2,1,3) #row vector
B<-t(B) #transpose

In [60]:
A
B

[,1] [,2] [,3]
[1,]  3    5    2  
[2,]  2   -3    1  
[3,] -5   -6   -3

[,1]
[1,] 3   
[2,] 4   
[3,] 5

In [61]:
di<-dim(B) #dimensions
di

[1] 3 1

In [62]:
d<-det(A) #determinant
d

[1] -4

In [63]:
C<-A%*%B #matrix multiplication

In [64]:
C

[,1]
[1,]  39 
[2,]  -1 
[3,] -54

In [65]:
I<-diag(3) #Identity matrix
I

[,1] [,2] [,3]
[1,] 1    0    0   
[2,] 0    1    0   
[3,] 0    0    1

In [75]:
e1<-I[1,]
e1

[1] 1 0 0

In [70]:
e1%*%A #extraccion de renglones

[,1] [,2] [,3]
[1,] 3    5    2

In [77]:
A%*%e1 #extraccion de columnas

[,1]
[1,]  3  
[2,]  2  
[3,] -5

In [78]:
e1<-I[2,]-I[3,]
e1%*%A #

[,1] [,2] [,3]
[1,] 7    3    4

In [236]:
vec<-c(0,0,0,1,-3,-6,1,1,1,2,3,4,5,6,7,8) #llenar por columnas
A<-matrix(vec,4,4) #matrix
A
det(A)

[,1] [,2] [,3] [,4]
[1,] 0    -3   1    5   
[2,] 0    -6   2    6   
[3,] 0     1   3    7   
[4,] 1     1   4    8

[1] 40

In [194]:
ol<-matrix(1,1,3) #renglones con ceros
or<-matrix(1,1,3)
or<-t(or)
mz<-A==0
colz<-(ol%*%mz)/3
renz<-(mz%*%or)/3

In [196]:
mz
colz
renz
mxc<-max(colz)
mxr<-max(renz)
mxc
mxr
if(mxr>mxc){#renglon
    i<-which(renz==mxr)
    j<-0
}else if(mxr<mxc){#columnas
    i<-0
    j<-which(colz==mxc)
}else{
    i<-0
    j<-0
}
i
j

[,1]  [,2]  [,3] 
[1,] FALSE FALSE FALSE
[2,] FALSE FALSE FALSE
[3,] FALSE FALSE FALSE

[,1] [,2] [,3]
[1,] 0    0    0

[,1]
[1,] 0   
[2,] 0   
[3,] 0

[1] 0

[1] 0

[1] 0

[1] 0

In [232]:
vec<-c(1,2,3,1,2,3,0,1,-3) #llenar por columnas
A<-matrix(vec,3,3) #matrix
A

[,1] [,2] [,3]
[1,] 1    1     0  
[2,] 2    2     1  
[3,] 3    3    -3

In [223]:
A[1,1]

[1] 1

In [142]:
ol<-matrix(1,1,3) #columnas repetidas
or<-matrix(1,1,3)
or<-t(or)
mrep<-A==A[,1]
colr<-(ol%*%mrep)/3
rengr<-(mrep%*%or)/3

In [145]:
mrep
sum(colr>=1)-1
sum(rengr>=1)

[,1] [,2] [,3] 
[1,] TRUE TRUE FALSE
[2,] TRUE TRUE FALSE
[3,] TRUE TRUE FALSE

[1] 1

[1] 0

In [3]:
check_mat<-function(A){#checa para cuando la matriz no es cuadrada, hay columnas o renglones completos con ceros o repetidos
    di<-dim(A)
    n<-di[1] #renglones
    m<-di[2] #columnas
    ol<-matrix(1,1,m) #vector renglon de 1's
    or<-matrix(1,n,1) #vector columna de 1's
    rorcr<-0 #inicia en cero el contador de columnas o renglones repetidos
    if(n!=m){#si no es matriz cuadrada
        cat("Error! Las dimensiones son diferentes \n")
        d<-(-1)
    }else{#checar si hay renglones o columnas completos con ceros
        mz<-A==0 #donde hay ceros
        colz<-(ol%*%mz)/n  #promedio columnas
        renz<-(mz%*%or)/m  #promedio renglones
        colz<-sum(colz>=1) #mas de una columna con ceros?
        renz<-sum(renz>=1) #mas de un renglon con ceros?
        if(colz>=1|renz>=1){#hay ceros en columnas o renglones completos?
            d<-0
        }else{#checa si hay columnas o renglones iguales
            i<-1
            while(rorcr==0&i<=n){
                
                #por renglones
                mrepr<-A==A[i,]
                rengr<-(mrepr%*%or)/m
                rengr<-sum(rengr>=1)-1
                
                #por columnas
                mrepc<-A==A[,i]
                colr<-(ol%*%mrepc)/n
                colr<-sum(colr>=1)-1
                i<-i+1
                if(rengr>=1|colr>=1){
                    rorcr<-1
                    d<-0
                }
                
            }

            
            
        }
        
    }
    d<-1#si no se cumplió ninguna de las condiciones
    return(d)

}

In [17]:
my_det<-function(A,ren=1,col=0){#calcula el determinante, por default para ren=1 si el usuario no ingresa nada
    ac<-0
    di<-dim(A) 
    n<-di[1] #renglones
    m<-di[2] #columnas
    ol<-matrix(1,1,m) #vector renglon de 1's
    or<-matrix(1,n,1) #vector columna de 1's
    dc<-check_mat(A)#checa para cuando la matriz no es cuadrada, hay columnas o renglones completos con ceros o repetidos
    if(dc==0){#filas o columnas con 0 o filas o columnas repetidas
        d<-0
    }else if(dc>0){#si no se cumple la condicion anterior
        if(n==2){#caso base
            d<-(A[1,1]*A[2,2])-(A[2,1]*A[1,2])
        }else{
            #determina fila o columna para calcular el determinante (con mas ceros)
            mz<-A==0 #donde hay ceros
            colz<-(ol%*%mz)/n  #promedio columnas
            renz<-(mz%*%or)/m  #promedio renglones
            mxc<-max(colz)
            mxr<-max(renz)
            if(mxr>mxc){#renglon con mas ceros
                i<-which(renz==mxr)
                j<-0
                ii<-which(A[i,]!=0)
            }else if(mxr<mxc){#columnas con mas ceros
                i<-0
                j<-which(colz==mxc)
                ii<-which(A[,j]!=0)
            }else{
                i<-ren
                j<-0
                ii<-which(A[i,]!=0)
            }


            if(i!=0){#por renglon
                for(j in ii){
                    aij=A[i,j]
                    c=(-1)^(i+j)
                    Aij=A[-i,-j]
                    daij<-my_det(Aij)
                    cij<-c*daij
                    
                    ac<-ac+(aij*cij)
                    
                    
                }

            }else if(j!=0){#por columna
                for(i in ii){
                    aij=A[i,j]
                    c=(-1)^(i+j)
                    Aij=A[-i,-j]
                    daij<-my_det(Aij)
                    cij<-c*daij
                    
                    ac<-ac+(aij*cij)
                    
                    
                }

            }
            d<-ac
            
            
        }

        

        
    }
    return(d)
    
}

In [18]:
vec<-c(0,0,0,1,-3,-6,1,1,1,2,3,4,5,6,7,8,22,23,2,1,5,4,3,2,1) #llenar por columnas
A<-matrix(vec,5,5) #matrix
A


[,1] [,2] [,3] [,4] [,5]
[1,]  0   -6   3     8   5   
[2,]  0    1   4    22   4   
[3,]  0    1   5    23   3   
[4,]  1    1   6     2   2   
[5,] -3    2   7     1   1

In [19]:
#A
my_det(A)
det(A)

[1] -5144

[1] -5144

In [28]:
vec<-c(2,4,-6,4,3,7,-10,6,0,2,0,4,0,0,1,5) #llenar por columnas
A<-matrix(vec,4,4) #matrix
A
det(A)

[,1] [,2] [,3] [,4]
[1,]  2     3  0    0   
[2,]  4     7  2    0   
[3,] -6   -10  0    1   
[4,]  4     6  4    5

[1] 12

In [32]:
i2<-which(abs(A[,1])==max(abs(A[,1]))) #encuentra el renglon a intercambiar
i2

[1] 3

In [ ]:
I<-diag(3) #Identity matrix

In [37]:
#intercambio de renglones
i1<-1
di<-dim(A)
n<-di[1] #renglones
m<-di[2] #columnas
I<-diag(x=1,n,m) #Identity matrix
I
vt<-matrix(0,1,m) #vector renglon de 0's
if(i1!=i2){
    vt=A[i1,]
    A[i1,]=A[i2,]
    A[i2,]=vt
}

[,1] [,2] [,3] [,4]
[1,] 1    0    0    0   
[2,] 0    1    0    0   
[3,] 0    0    1    0   
[4,] 0    0    0    1

[,1] [,2] [,3] [,4]
[1,] -6   -10  0    1   
[2,]  4     7  2    0   
[3,]  2     3  0    0   
[4,]  4     6  4    5

In [25]:
swaprows<-function(p,r1,r2){
    di<-dim(p)
    n<-di[1] #renglones
    m<-di[2] #columnas
    #I<-diag(x=1,n,m) #Identity matrix
    vt<-matrix(0,1,m) #vector renglon de 0's
    if(r1!=r2){
        vt=I[r1,]
        p[r1,]=I[r2,]
        p[r2,]=vt
    }
    return(I)
    
}

In [11]:
A #intercambio de renglones
I<-swaprows(4,4,2,4)
I%*%A

[,1] [,2] [,3] [,4]
[1,]  2     3  0    0   
[2,]  4     7  2    0   
[3,] -6   -10  0    1   
[4,]  4     6  4    5

[,1] [,2] [,3] [,4]
[1,]  2     3  0    0   
[2,]  4     6  4    5   
[3,] -6   -10  0    1   
[4,]  4     7  2    0

In [22]:

di<-dim(A)
n<-di[1] #renglones
m<-di[2] #columnas
I<-diag(x=1,n,m) #Identity matrix
z<-matrix(0,n,m) #vector renglon de 1's
l<-matrix(0,n,m) #vector renglon de 1's
li<-matrix(0,n,m) #vector renglon de 1's
u<-matrix(0,n,m) #vector renglon de 1's


In [17]:
lowerZ<-function(A,j){
    di<-dim(A)
    n<-di[1] #renglones
    m<-di[2] #columnas
    z<-matrix(0,n,m) #vector renglon de 1's
    i<-1:j
    z[-i,j]<-A[-i,j]
    return(z)
    
}

In [19]:
j<-1
pivot<-A[j,j]
tk<-lowerZ(A,j)/pivot

In [20]:
tk

[,1] [,2] [,3] [,4]
[1,]  0   0    0    0   
[2,]  2   0    0    0   
[3,] -3   0    0    0   
[4,]  2   0    0    0

In [23]:
li<-I-tk
li

[,1] [,2] [,3] [,4]
[1,]  1   0    0    0   
[2,] -2   1    0    0   
[3,]  3   0    1    0   
[4,] -2   0    0    1

In [24]:
li%*%A

[,1] [,2] [,3] [,4]
[1,] 2     3   0    0   
[2,] 0     1   2    0   
[3,] 0    -1   0    1   
[4,] 0     0   4    5

In [135]:
swaprows<-function(p,r1,r2){#devuelve la matriz de permutación
    di<-dim(p)
    n<-di[1] #renglones
    m<-di[2] #columnas
    #I<-diag(x=1,n,m) #Identity matrix
    vt<-matrix(0,1,m) #vector renglon de 0's
    if(r1!=r2){
        vt=I[r1,] #vector temporal
        p[r1,]=I[r2,] #intercambia renglones
        p[r2,]=vt
    }
    return(I)
    
}

lowerZ<-function(A,j){#devuelve una matriz de ceros excepto los elementos debajo del pivote
    di<-dim(A)
    n<-di[1] #renglones
    m<-di[2] #columnas
    z<-matrix(0,n,m) #vector renglon de 1's
    i<-1:j
    z[-i,j]<-A[-i,j] #selecciona elementos debajo del pivote
    return(z)
    
}

my_lu<-function(A){#resuleve
    di<-dim(A) #dimensiones
    n<-di[1] #renglones
    m<-di[2] #columnas
    if(n==m){
        z<-matrix(0,n,m) #vector renglon de 0's
        l<-z #inicializa matrices y vectores
        u<-z
        tk<-z
        li<-z
        I<-diag(x=1,n,m) #Identity matrix
        p<-I
        i<-0
        j<-0
        pivot<-0

        #realiza el esscalonamiento por lu
        for(j in 1:n){
            pivot<-A[j,j] #pivote

            if(pivot!=0){#sin hacer cambios de renglon
                tk<-lowerZ(A,j)/pivot  #obtiene los elementos debajo del pivote
                li<-I-tk #matriz del tipo 3
                A<-li%*%A #se eliminan los elementos debajo del pivote

            }else if(pivot==0){#cambios de renglon (el de mayor magnitud)
                r1<-j
                r2<-which(abs(A[,j])==max(abs(A[,j]))) #encuentra el renglon a intercambiar
                p<-swaprows(p,r1,r2)
                A<-p%*%A#intercambia los renglones

                pivot<-A[j,j]

                if(pivot!=0){
                    tk<-lowerZ(A,j)/pivot
                    li<-I-tk
                    A<-li%*%A
                }



            }

            z<-z+tk #acumula los elementos debajo del pivote

        }
        l<-I+z #obtiene la matriz l
        u<-A #u
        vres <- list(p,l, u)
        
        return(vres)
        
    }
    
}



In [131]:
?attach

In [178]:
my_forwards<-function(l,b){
    n<-length(b)
    y<-matrix(0,1,n) #vector renglon de 0's
    
    y[1]<-b[1]
    
    for(i in 2:n){
        suma<-0
        for( j in 1:(i-1)){
            suma<-suma+(l[i,j]*y[j])
        
        }
        y[i]<-b[i]-suma
        
    }
    return(y)
}

my_backs<-function(u,y){
    n<-length(y)
    x<-matrix(0,1,n) #vector renglon de 0's
    
    x[n]<-y[n]/u[n,n]
    
    
    i<-n-1
    while(i>=1){
        
        suma<-0
        for( j in 1:(i+1)){
            suma<-suma+(u[i,j]*x[j])
        
        }
        x[i]<-(1/u[i,i])*(y[i]-suma)
        
        i<-i-1
    }
    return(x)
}

my_solve<-function(l,u,b){
    y<-my_forwards(l,b)
    cat(b,"\n")
    cat(y,"\n")
    x<-my_backs(u,y)
    cat(x,"\n")
    return(x)
}

In [179]:
vec<-c(2,4,-6,4,3,7,-10,6,0,2,0,4,0,0,1,5) #llenar por columnas
A<-matrix(vec,4,4) #matrix

B<-c(1,2,1,0) #vector

listt<-my_lu(A)
l<-listt[[2]]
u<-listt[[3]]
x<-my_solve(l,u,B)

1 2 1 0 
1 0 4 -10 
11.5 -7.333333 3.666667 -3.333333 


In [156]:
A
B
l
u
x

[,1] [,2] [,3] [,4]
[1,]  2     3  0    0   
[2,]  4     7  2    0   
[3,] -6   -10  0    1   
[4,]  4     6  4    5

[,1]
[1,] 1   
[2,] 2   
[3,] 1   
[4,] 0

[,1] [,2] [,3] [,4]
[1,]  1    0   0    0   
[2,]  2    1   0    0   
[3,] -3   -1   1    0   
[4,]  2    0   2    1

[,1] [,2] [,3] [,4]
[1,] 2    3    0    0   
[2,] 0    1    2    0   
[3,] 0    0    2    1   
[4,] 0    0    0    3

[,1]
[1,] -1.5
[2,]  1.0
[3,]  0.5
[4,]  0.0

In [62]:
vec<-c(2,4,-6,4,3,7,-10,6,0,2,0,4,0,0,1,5) #llenar por columnas
A<-matrix(vec,4,4) #matrix
A
det(A)
my_lu(A)

[,1] [,2] [,3] [,4]
[1,]  2     3  0    0   
[2,]  4     7  2    0   
[3,] -6   -10  0    1   
[4,]  4     6  4    5

[1] 12

[[1]]
     [,1] [,2] [,3] [,4]
[1,]    1    0    0    0
[2,]    0    1    0    0
[3,]    0    0    1    0
[4,]    0    0    0    1

[[2]]
     [,1] [,2] [,3] [,4]
[1,]    1    0    0    0
[2,]    2    1    0    0
[3,]   -3   -1    1    0
[4,]    2    0    2    1

[[3]]
     [,1] [,2] [,3] [,4]
[1,]    2    3    0    0
[2,]    0    1    2    0
[3,]    0    0    2    1
[4,]    0    0    0    3

In [58]:
vec<-c(2,2,4,0,-2,-1,-1,1,-5,-3,-4,2,-3,2,10,5,-1,3,11,4,2,2,4,0) #llenar por columnas
A<-matrix(vec,4,6) #matrix
A
det(A)
my_lu(A)

[,1] [,2] [,3] [,4] [,5] [,6]
[1,] 2    -2   -5   -3   -1   2   
[2,] 2    -1   -3    2    3   2   
[3,] 4    -1   -4   10   11   4   
[4,] 0     1    2    5    4   0

[1] 2


ERROR: Error in li %*% A: argumentos no compatibles
